### PR TITLE
Changed COMMIT

### PR DESCRIPTION
**Pull request by atb299**
Latest changes only affect docs

Checklist:
- [x] Setup script works OK: `./setup`
- [ ] `AGRIF_QCO/GSRIDGE36Zx2-GIBSTRA36Zx2/` runs OK
- [ ] All namelists have been updated: `./scripts/update_namelists`

Closes https://github.com/immerse-project/wp6.2-demonstrator/issues/33
Closes https://github.com/immerse-project/wp6.2-demonstrator/issues/32

### CODE REVIEW

**Review by malmans2 — APPROVED** [review]
@atb299 if you edit your PR message and you add the following, the issues will be closed when you merge.
Closes #33
Closes #32

**Comment by atb299** [comment]
@malmans2 , thanks. I will check (to be sure) that I can run setup and the model runs before I merge.

**Comment by atb299** [comment]
Model doesn't run at the moment. ocean.output gets to:

...
 weight file:  ./INPUT/JRA/weights_jra_eORCA12_bicubic.nc
       ddims:           640         320
      numwgt:            16
      jpiwgt:             9
      jpjwgt:             3
     botleft:           130          10
    topright:           138          12
        cyclical
        allocated
 weight file:  ./INPUT/JRA/weights_jra_eORCA12_bilin.nc
       ddims:           640         320


Will investigate whether the weights built correctly.

**Comment by malmans2** [comment]
It's this issue: https://github.com/immerse-project/wp6.2-demonstrator/issues/37#issuecomment-1048891126

Something about the ice xml is not compatible with AGRIF.

**Comment by atb299** [comment]
I see. I've cut the ice xml down and resubmitted.

**Pull request merged**
