### PR TITLE
Align with ACSIS

### LINKED ISSUE #30: Comparison commit e6121074 and 9df45b62
Hi there,
commit [e6121074](https://forge.nemo-ocean.eu/nemo/core/-/commit/e61210740c49fae3b58fd93fc8d482c1e3da51e5) has been pushed. [Here](https://forge.nemo-ocean.eu/nemo/nemo/-/compare/9df45b62a4f88f4d0e29c7f6ef2974e80939618b...e61210740c49fae3b58fd93fc8d482c1e3da51e5) is the comparison with the commit currently used.

🚀THERE ARE NO CONFLICTS🚀
Consider setting `COMMIT=e61210740c49fae3b58fd93fc8d482c1e3da51e5` in the [setup script](https://github.com/immerse-project/wp6.2-demonstrator/blob/main/scripts/setup).

### PR DESCRIPTION
**Pull request by malmans2**
Checklist:
- [x] Setup script works OK: `./setup`
- [x] `AGRIF_QCO/GSRIDGE36Zx2-GIBSTRA36Zx2/` runs OK
- [ ] All namelists have been updated: `./scripts/update_namelists`

Closes #30

### CODE REVIEW

**Comment by malmans2** [comment]
@atb299 whenever you get a chance, could you take a look at [this file](https://github.com/immerse-project/wp6.2-demonstrator/blob/xios_xml/cfgs/AGRIF_QCO/GSRIDGE36Zx2-GIBSTRA36Zx2/file_def_nemo-oce.xml) please?

No rush! I'll take another look with fresh eyes next week and I'll add ice as well.

The idea is to align as much as possible with `/work/n01/n01/alexm/NEMO/NEMO_4.0.4_GO8p7_wkg/cfgs/GO8p7/GO8p7_eORCA12/file_def_nemo-oce-ACSIS.xml`

**Comment by malmans2** [comment]
@atb299 the [ice file](https://github.com/immerse-project/wp6.2-demonstrator/blob/xios_xml/cfgs/AGRIF_QCO/GSRIDGE36Zx2-GIBSTRA36Zx2/file_def_nemo-ice.xml) is also ready for review.

**Comment by atb299** [comment]
@malmans2 The xml files look good. One question: does it make sense to output potential T as well as conservative T? I think we discussed this, and given we're thinking of relatively short runs I think it's worth the additional disk use to output as we go.

**Comment by malmans2** [comment]
@atb299 Done!

**Pull request merged**
